name: Demo Workflow
on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print first job
        run: echo "First job!"
  one-half-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Print one half job
        run: echo "One half job!"
  one-half-two-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Print one half two job
        run: echo "One half two job!"
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Print second job
        run: echo "Second job!"
  second-half-job:
    runs-on: ubuntu-latest
    needs: second-job
    steps:
      - name: Print second half job
        run: echo "Second half job!"
  third-job:
    runs-on: ubuntu-latest
    needs: second-job
    steps:
      - name: Print github metadata
        run: echo "${{toJson(github)}}"
  final-job:
    runs-on: ubuntu-latest
    needs: third-job
    steps:
      - name: Print final job
        run: echo "Final job!"
      - name: Print ending
        run: echo "Done! Good bye!"
